### ISSUE TITLE
Invalid Syntax Error

### ISSUE THREAD

**Issue by erwincoumans** [gosha20777/keras2cpp#7]
Thanks for sharing this interesting project!

Ubuntu, Python 3.5.4, Keras 2.2.4
running python3 python_model.py returns this error:
~~~~~~~~~~~
Traceback (most recent call last):
  File "python_model.py", line 22, in <module>
    from keras2cpp import export_model
  File "/usr/local/google/home/erwincoumans/develop/keras2cpp/keras2cpp.py", line 60
    f.write(struct.pack(f'={remaining}f', *data[i: i + remaining]))
                                       ^
SyntaxError: invalid syntax

~~~~~~~~~~~~~~

Do you have any idea what this is about?

**Comment by gosha20777** [comment]
Please try to use Python 3.6

**Comment by miqianmimi** [comment]
from keras2cpp import export_model

**Comment by miqianmimi** [comment]
from keras2cpp import export_model
ImportError: cannot import name 'export_model'
